version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: flashcard-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashcard
    ports:
        - "5432:5432"
    networks:
        - postgres-db-network

networks:
  postgres-db-network:
    driver: bridge